version: "3.8"
services:
  job-site-api:
    build: .
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER}
    expose:
      - ${REDIS_PORT}

  postgres:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - ${PGADMIN_PORT}:80

volumes:
  postgres-volume:
    external: false
    name: ${POSTGRES_VOLUME}
